PedidoCigarro/Controllers/CorredoresController.cs
using Newtonsoft.Json;
using PedidoCigarro.Contexts;
using PedidoCigarro.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace PedidoCigarro.Controllers
{
    [HandleError]
    public class CorredoresController : Controller
    {
        private EFContext context = new EFContext();

        // GET: Corredores
        public ActionResult Index()
        {
            return View(context.Corredor.OrderBy(c => c.IdCorredor));
            //return View(context.Corredor.OrderBy(c => c.IdCorredor));
        }

        // GET Detalhes
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Corredor corredor = context.Corredor.Find(id);
            if (corredor == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            return View(corredor);
        }

        // GET Criar
        public ActionResult Criar()
        {
            return View();
        }

        // POST Criar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(Corredor corredor)
        {
            try
            {
                context.Corredor.Add(corredor);
                context.SaveChanges();
                TempData["Mensagem"] = "Dados inseridos com sucesso.";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Erro de inserção.";
                return View(corredor);
            }
        }

        // GET Editar
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Corredor corredor = context.Corredor.Find(id);
            if (corredor == null)
            {
                //return HttpNotFound();
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            return View(corredor);
        }

        // POST Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Corredor corredor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Entry(corredor).State = EntityState.Modified;
                    context.SaveChanges();
                    TempData["Mensagem"] = "Dados alterados com sucesso.";
                    return RedirectToAction("Index");
                }
                return View(corredor);
            }
            catch
            {
                TempData["Mensagem"] = "Dados não puderam ser alterados.";
                return View(corredor);
            }

        }

        // GET Deletar
        public ActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Corredor corredor = context.Corredor.Find(id);
            if (corredor == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            return View(corredor);
        }

        // POST Deletar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletar(int id)
        {
            try
            {
                Corredor corredor = context.Corredor.Find(id);
                context.Corredor.Remove(corredor);
                context.SaveChanges();
                TempData["Mensagem"] = corredor.NomeCorredor + " foi removido com sucesso.";

                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Dados não puderam ser deletados.";
                return View();
            }
        }

        //public ActionResult Grafico()
        //{
        //    new Chart(1600, 900, ChartTheme.Vanilla)
        //        .AddTitle("Quem corre mais?")
        //        .DataBindTable(context.Corredor, "QtdePedidos")
        //        .Write("png");
        //    return View(context.Corredor);
        //}

        public ActionResult Grafico()
        {
            ViewBag.Valores = JsonConvert.SerializeObject(context.Corredor.ToList());
            return View();
        }
    }
}

PedidoCigarro/Controllers/PedidosController.cs
using PedidoCigarro.Contexts;
using PedidoCigarro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace PedidoCigarro.Controllers
{
    [HandleError]
    public class PedidosController : Controller
    {
        private EFContext context = new EFContext();

        // GET: Pedidos
        public ActionResult Index()
        {
            var pedidos = context.Pedido.Include(c => c.Corredor).Include(f => f.Cigarro).OrderBy(n => n.IdPedido);
            return View(pedidos);
        }

        // GET Detalhes
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Pedido pedido = context.Pedido.Find(id);
            if (pedido == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "IdCigarro", pedido.IdCigarro);
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "IdCorredor", pedido.IdCorredor);
            return View(pedido);
        }

        // GET Criar
        public ActionResult Criar()
        {
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "NomeCigarro");
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "NomeCorredor");
            return View();
        }

        // POST Criar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(Pedido pedido)
        {
            try
            {
                context.Pedido.Add(pedido);
                context.SaveChanges();
                TempData["Mensagem"] = "Dados inseridos com sucesso.";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Erro de inserção.";
                return View(pedido);
            }

        }

        // GET Editar
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = context.Pedido.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "IdCigarro", pedido.IdCigarro);
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "IdCorredor", pedido.IdCorredor);
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Pedido pedido)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Entry(pedido).State = EntityState.Modified;
                    context.SaveChanges();
                    TempData["Mensagem"] = "Dados alterados com sucesso.";
                    return RedirectToAction("Index");
                }
                return View(pedido);
            }
            catch
            {
                return View(pedido);
            }
        }

        public ActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Pedido pedido = context.Pedido.Find(id);
            if (pedido == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "IdCigarro", pedido.IdCigarro);
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "IdCorredor", pedido.IdCorredor);
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletar(int id)
        {
            try
            {
                Pedido pedido = context.Pedido.Find(id);
                context.Pedido.Remove(pedido);
                context.SaveChanges();
                TempData["Mensagem"] = pedido.NomePedido + " foi removido com sucesso.";

                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Dados não puderam ser deletados.";
                return View();

            }
        }
    }
}

PedidoCigarro/Views/Corredores/Criar.cshtml
@model PedidoCigarro.Models.Corredor

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.NomeCorredor, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NomeCorredor, new { htmlAttributes = new { @class = "form-control", placeholder = "Nome do Corredor" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Carro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "form-control", placeholder = "Carro" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtdePedidos)
        @Html.EditorFor(model => model.QtdePedidos, new { htmlAttributes = new { @class = "form-control", placeholder = "Quantidade de Pedidos" } })
    </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                <input type="submit" value="Adicionar Corredor" class="btn btn-success btn-lg btn-block" />
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Corredor", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Corredores/Deletar.cshtml
@model PedidoCigarro.Models.Corredor

@{
    ViewBag.Title = "Deletar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deletar</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.IdCorredor, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.IdCorredor, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NomeCorredor, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NomeCorredor, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Carro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtdePedidos)
        @Html.EditorFor(model => model.QtdePedidos, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                <input type="submit" value="Deletar corredor" class="btn btn-danger btn-lg btn-block" />
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Corredor", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Corredores/Detalhes.cshtml
@model PedidoCigarro.Models.Corredor

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.IdCorredor, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.IdCorredor, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NomeCorredor, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NomeCorredor, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Carro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtdePedidos)
        @Html.EditorFor(model => model.QtdePedidos, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                @Html.ActionLink("Editar", "Editar", new { id = Model.IdCorredor }, new { @class = "btn btn-primary btn-lg btn-block" })
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Corredor", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Corredores/Editar.cshtml
@model PedidoCigarro.Models.Corredor

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.IdCorredor, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.IdCorredor, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        @Html.HiddenFor(model => model.IdCorredor)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NomeCorredor, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NomeCorredor, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Carro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Carro, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtdePedidos)
        @Html.EditorFor(model => model.QtdePedidos, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                <input type="submit" value="Salvar Alterações" class="btn btn-success btn-lg btn-block" />
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Corredores", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Corredores/Grafico.cshtml
@{
    ViewBag.Title = "Gráfico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script>
    window.onload = function () {

    var chart = new CanvasJS.Chart("chartContainer", {
        animationEnabled: true,
        theme: "light2", // "light1", "dark1", "dark2"
        exportEnabled: true,
        title: {
            text: "Corredores com a maior quantidade de pedidos"
        },
        data: [{
            type: "column",
            dataPoints:  @Html.Raw(ViewBag.Valores),
        }]
    });
    chart.render();

    }
    </script>
}
<h2>Grafico</h2>
<hr />

<div class="container">
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
</div>

<div class="container mt-4">
    <div class="row">
        <div class="col">
            @Html.ActionLink("Novo Corredor", "Criar", "Corredor", new { @class = "btn btn-primary btn-lg btn-block" })
        </div>
        <div class="col">
            @Html.ActionLink("Voltar", "Index", "Corredores", new { @class = "btn btn-secondary btn-lg btn-block" })
        </div>
    </div>
</div>

PedidoCigarro/Views/Corredores/Index.cshtml
@model IEnumerable<PedidoCigarro.Models.Corredor>

@{
    ViewBag.Title = "Lista de Corredores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function ($) {
            $(".d-table-row").click(function () {
                window.document.location = $(this).data("href");
            });
            $(".d-table-row").css("cursor", "pointer");
        });
    </script>
}

<h2>Todos os Corredores</h2>
<hr />

@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-secondary" role="alert">
        @TempData["Mensagem"]
    </div>
}


<table class="table table-bordered text-center table-hover">
    <thead class="thead-dark font-weight-normal">
        <tr>
            <th scope="col" class="font-weight-normal">
                @Html.DisplayNameFor(model => model.NomeCorredor)
            </th>
            <th scope="col" class="font-weight-normal">
                @Html.DisplayNameFor(model => model.Carro)
            </th>
            <th scope="col" class="font-weight-normal">
                @Html.DisplayNameFor(model => model.QtdePedidos)
            </th>
            <th scope="col" class="font-weight-normal">Funções</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="d-table-row" data-href="@Url.Action("Detalhes", "Corredores", new { id = item.IdCorredor })">
                <th scope="row" class="font-weight-normal">
                    @Html.DisplayFor(modelItem => item.NomeCorredor)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Carro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QtdePedidos)
                </td>
                <td>
                    <div class="btn-group" role="group">
                        <a href="@Url.Action("Editar", "Corredores", new { id = item.IdCorredor })" type="button" class="btn btn-secondary">Editar</a>
                        <a href="@Url.Action("Deletar", "Corredores", new { id = item.IdCorredor })" type="button" class="btn btn-danger">Deletar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="container">
    <div class="row">
        <div class="col">
            @Html.ActionLink("Novo corredor", "Criar", "Corredor", new { @class = "btn btn-primary btn-lg btn-block" })
        </div>
        <div class="col">
            @Html.ActionLink("Gráfico", "Grafico", "Corredor", new { @class = "btn btn-secondary btn-lg btn-block" })
        </div>
        <div class="col">
            @Html.ActionLink("Voltar", "Index", "Pedidos", "Pedidos", new { @class = "btn btn-secondary btn-lg btn-block" })
        </div>
    </div>
</div>