PedidoCigarro/Models/Cigarro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using PedidoCigarro.Models;

namespace PedidoCigarro.Models
{
    public class Cigarro
    {
        [Key]
        [Display(Name = "Registro")]
        public int? IdCigarro { get; set; }

        [Required]
        [MaxLength(200), MinLength(3)]
        [Display(Name = "Cigarro")]
        public string NomeCigarro { get; set; }

        [Required]
        [MaxLength(200), MinLength(3)]
        [Display(Name = "Marca")]
        public string Marca { get; set; }

        [Required]
        [MaxLength(200), MinLength(3)]
        [Display(Name = "Empresa")]
        public string Empresa { get; set; }

        public ICollection<Pedido> Pedidos { get; set; }
    }
}

PedidoCigarro/Controllers/CigarrosController.cs
using PedidoCigarro.Contexts;
using PedidoCigarro.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PedidoCigarro.Controllers
{
    [HandleError]
    public class CigarrosController : Controller
    {
        private EFContext context = new EFContext();

        // GET: Cigarros
        public ActionResult Index()
        {
            return View(context.Cigarro.OrderBy(c => c.IdCigarro));
        }

        // GET Detalhes
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Cigarro cigarro = context.Cigarro.Find(id);
            if (cigarro == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            return View(cigarro);
        }

        // GET Criar
        public ActionResult Criar()
        {
            return View();
        }

        // POST Criar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(Cigarro cigarro)
        {
            try
            {
                context.Cigarro.Add(cigarro);
                context.SaveChanges();
                TempData["Mensagem"] = "Dados inseridos com sucesso.";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Erro de inserção.";
                return View(cigarro);
            }
        }

        // GET Editar
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Cigarro cigarro = context.Cigarro.Find(id);
            if (cigarro == null)
            {
                //return HttpNotFound();
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            return View(cigarro);
        }

        // POST Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Cigarro cigarro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Entry(cigarro).State = EntityState.Modified;
                    context.SaveChanges();
                    TempData["Mensagem"] = "Dados alterados com sucesso.";
                    return RedirectToAction("Index");
                }
                return View(cigarro);
            }
            catch
            {
                TempData["Mensagem"] = "Dados não puderam ser alterados.";
                return View(cigarro);
            }

        }

        // GET Deletar
        public ActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Cigarro cigarro = context.Cigarro.Find(id);
            if (cigarro == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            return View(cigarro);
        }

        // POST Deletar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletar(int id)
        {
            try
            {
                Cigarro cigarro = context.Cigarro.Find(id);
                context.Cigarro.Remove(cigarro);
                context.SaveChanges();
                TempData["Mensagem"] = cigarro.NomeCigarro + " foi removido com sucesso.";

                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Dados não puderam ser Deletados.";
                return View();
            }
        }
    }
}

PedidoCigarro/Controllers/PedidosController.cs
using PedidoCigarro.Contexts;
using PedidoCigarro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace PedidoCigarro.Controllers
{
    [HandleError]
    public class PedidosController : Controller
    {
        private EFContext context = new EFContext();

        // GET: Pedidos
        public ActionResult Index()
        {
            var pedidos = context.Pedido.Include(c => c.Corredor).Include(f => f.Cigarro).OrderBy(n => n.IdPedido);
            return View(pedidos);
        }

        // GET Detalhes
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Pedido pedido = context.Pedido.Find(id);
            if (pedido == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "IdCigarro", pedido.IdCigarro);
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "IdCorredor", pedido.IdCorredor);
            return View(pedido);
        }

        // GET Criar
        public ActionResult Criar()
        {
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "NomeCigarro");
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "NomeCorredor");
            return View();
        }

        // POST Criar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(Pedido pedido)
        {
            try
            {
                context.Pedido.Add(pedido);
                context.SaveChanges();
                TempData["Mensagem"] = "Dados inseridos com sucesso.";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Erro de inserção.";
                return View(pedido);
            }

        }

        // GET Editar
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = context.Pedido.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "IdCigarro", pedido.IdCigarro);
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "IdCorredor", pedido.IdCorredor);
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Pedido pedido)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Entry(pedido).State = EntityState.Modified;
                    context.SaveChanges();
                    TempData["Mensagem"] = "Dados alterados com sucesso.";
                    return RedirectToAction("Index");
                }
                return View(pedido);
            }
            catch
            {
                return View(pedido);
            }
        }

        public ActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("SolicitacaoInvalida", "Erro");
            }
            Pedido pedido = context.Pedido.Find(id);
            if (pedido == null)
            {
                return RedirectToAction("NaoEncontrado", "Erro");
            }
            ViewBag.IdCigarro = new SelectList(context.Cigarro.OrderBy(c => c.IdCigarro), "IdCigarro", "IdCigarro", pedido.IdCigarro);
            ViewBag.IdCorredor = new SelectList(context.Corredor.OrderBy(c => c.IdCorredor), "IdCorredor", "IdCorredor", pedido.IdCorredor);
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletar(int id)
        {
            try
            {
                Pedido pedido = context.Pedido.Find(id);
                context.Pedido.Remove(pedido);
                context.SaveChanges();
                TempData["Mensagem"] = pedido.NomePedido + " foi removido com sucesso.";

                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Mensagem"] = "Dados não puderam ser deletados.";
                return View();

            }
        }
    }
}

PedidoCigarro/Views/Cigarros/Criar.cshtml
@model PedidoCigarro.Models.Cigarro

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.NomeCigarro, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.NomeCigarro, new { htmlAttributes = new { @class = "form-control", placeholder = "Nome do Cigarro" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control", placeholder = "Marca" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa)
            @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control", placeholder = "Empresa Fabricante" } })
        </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                <input type="submit" value="Adicionar Cigarro" class="btn btn-success btn-lg btn-block" />
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Cigarros", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Cigarros/Deletar.cshtml
@model PedidoCigarro.Models.Cigarro

@{
    ViewBag.Title = "Deletar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deletar</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.IdCigarro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.IdCigarro, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NomeCigarro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NomeCigarro, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Empresa)
        @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                <input type="submit" value="Deletar cigarro" class="btn btn-danger btn-lg btn-block"  />
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Cigarros", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Cigarros/Detalhes.cshtml
@model PedidoCigarro.Models.Cigarro

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.IdCigarro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.IdCigarro, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NomeCigarro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NomeCigarro, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Empresa)
        @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                @Html.ActionLink("Editar", "Editar", new { id = Model.IdCigarro }, new { @class = "btn btn-primary btn-lg btn-block" })
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Cigarros", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Cigarros/Editar.cshtml
@model PedidoCigarro.Models.Cigarro

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.IdCigarro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.IdCigarro, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        @Html.HiddenFor(model => model.IdCigarro)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NomeCigarro, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NomeCigarro, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Empresa)
        @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="container mb-3">
        <div class="row">
            <div class="col">
                <input type="submit" value="Salvar Alterações" class="btn btn-success btn-lg btn-block" />
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "Cigarros", new { @class = "btn btn-secondary btn-lg btn-block" })
            </div>
        </div>
    </div>
}

PedidoCigarro/Views/Cigarros/Index.cshtml
@model IEnumerable<PedidoCigarro.Models.Cigarro>

@{
    ViewBag.Title = "Lista de Cigarros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function ($) {
            $(".d-table-row").click(function () {
                window.document.location = $(this).data("href");
            });
            $(".d-table-row").css("cursor", "pointer");
        });
    </script>
}

<h2>Todos os cigarros</h2>
<hr />

@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-secondary" role="alert">
        @TempData["Mensagem"]
    </div>
}


<table class="table table-bordered text-center table-hover">
    <thead class="thead-dark font-weight-normal">
        <tr>
            <th scope="col" class="font-weight-normal">
                @Html.DisplayNameFor(model => model.NomeCigarro)
            </th>
            <th scope="col" class="font-weight-normal">
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th scope="col" class="font-weight-normal">
                @Html.DisplayNameFor(model => model.Empresa)
            </th>
            <th scope="col" class="font-weight-normal">Funções</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="d-table-row" data-href="@Url.Action("Detalhes", "Cigarros", new { id = item.IdCigarro })">
                <th scope="row" class="font-weight-normal">
                    @Html.DisplayFor(modelItem => item.NomeCigarro)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Empresa)
                </td>
                <td>
                    <div class="btn-group" role="group">
                        <a href="@Url.Action("Editar", "Cigarros", new { id = item.IdCigarro })" type="button" class="btn btn-secondary">Editar</a>
                        <a href="@Url.Action("Deletar", "Cigarros", new { id = item.IdCigarro })" type="button" class="btn btn-danger">Deletar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="container">
    <div class="row">
        <div class="col">
            @Html.ActionLink("Novo cigarro", "Criar", "Cigarro", new { @class = "btn btn-primary btn-lg btn-block" })
        </div>
        <div class="col">
            @Html.ActionLink("Voltar", "Index", "Pedidos", "Pedidos", new { @class = "btn btn-secondary btn-lg btn-block" })
        </div>
    </div>

</div>